version: '3'
services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    image: alhoqbani/opencart
    ports:
     - "${APP_PORT:-80}:80"
    environment:
      CONTAINER_ENV: "${APP_ENV:-local}"
      XDEBUG_HOST: "${XDEBUG_HOST}"
      WWWUSER: "${WWWUSER}"
    volumes:
     - .:/var/www/html
    networks:
     - net
  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
      args:
        uid: "${WWWUSER}"
    image: alhoqbani/node
    user: node
    volumes:
     - .:/var/www/html
    networks:
     - net
  mysql:
    image: mysql:5.7
    ports:
     - "${MYSQL_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD:-secret}"
      MYSQL_DATABASE: "${DB_DATABASE:-opencart}"
      MYSQL_USER: "${DB_USERNAME:-opencart}"
      MYSQL_PASSWORD: "${DB_PASSWORD:-secret}"
    volumes:
     - mysql_data:/var/lib/mysql
     # - ./docker/mysql/conf.d:/etc/mysql/conf.d
     # - ./docker/mysql/logs:/var/log/mysql
    networks:
     - net
  redis:
    image: redis:alpine
    volumes:
     - redis_data:/data
    networks:
     - net
networks:
  net:
    driver: "bridge"
volumes:
  mysql_data:
    driver: "local"
  redis_data:
    driver: "local"
